### ISSUE TITLE
Implement logic for adding calories

### ISSUE THREAD

**Issue by Dri-water** [AY2425S1-CS2113-W12-1/tp#3]

**Comment by DarkDragoon2002** [comment]
- [x] Implement Add Calories
- [x] Implement Delete Calories

**Comment by kennethSty** [comment]
- Adding calories and meals is done. 
Note: Instead of using a second calorie class and duplicating code from the meal class, I made the name of a meal `Optional<String>`. The `MealEntry` class inherits from the `Meal` class. This way we do not need two distinct objects for tracking meal entries with and without a name. 
- To track calorie history meals are added into a `mealEntries` instance of `MealEntriesList`. To implement the deletion you can simply add the command to the `MealEntriesList` class or preferably in its superclass `MealList`. Then implement the logic when the deletion is conducted in the `ChatParser` class.

**Comment by ryryry-3302** [comment]
ill be yoinking Delete calories
